language: node_js
node_js: 10.12.0
before_install:
- yarn global add greenkeeper-lockfile@1
- npm config set spin false --global
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
env:
  global:
    secure: M51TJ/9pQNLsTkStCGCvnIS1249OQwo1o4MRz9oDEmRYrBcFxKU7JoU1Jz561n/XXfaHsL/N9eXt9+alHhEHoe7l5muOQQKCyEC7EIX1kSjMihDkMNIeQfNN3CD4ogUZ7BZ2nQIzPMqKR3nUq6MlotxyN3elSqBlx15bU9u8Jn4+4nnhaj6Y393CGHCJORddhFiT8Ks2l9Fbhot4cfv15DMfrM3hWHOfLfvH8c/pGSyfF1bzmUFgEr+zqEYQxAYo26SRwy1zf5dJ93P7ezHiF9bZyjf/H1G5K5Cio7LmhBc3G27JxJ/QcUvre/oivBrDqqJ5Qy9uQ1mwtPpZ/OQJ3P9w1ZD2z/vaJyeUGzAL1kW4sevQGXCAuzT+67PE36PVyK9Z2AtmpI1etoxFlASRuLEnHDo4dj7I1bJN38xRZoIRmmhV0LGC4+qb6KkEcsAakuTp5G7WM4RrsNkf9kf6HOyzAXnrXPO6g2nwOtVgUohr1iCoFjfgG8BXPzRVTQcc33hrbkRslIFQv20xil4MYOZL8PlYT28iPx3BnLhiMUtnWH5D5aUxASAu0vHz5yXxe/kVGQINgkrRGqH8IYqCs4cdzoRd6vgFccEtrAHKRJ9jGVfA7nojTnSuBZ7cYDRYtqZqt2STKYyXHNKwMXinaHqeNq3wtv8iNhU2CRIzd98=
